version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    app:
        build:
        context: .
        dockerfile: Dockerfile
        container_name: nest-app
        environment:
        DATABASE_URL: postgres://postgres:postgres@db:5432/nest
        JWT_SECRET: your-secret
        ports:
        - "3000:3000"
        depends_on:
        - db
volumes:
  db-data: